-- Catálogo global: estructura oficial del Formulario 103 (SRI)
-- Transcrito de "SRI GUIA TECNICA/formulario103.xls" (Resolución NAC-DGERCGC16-00000125).
-- Es un catálogo GLOBAL (no lleva id_empresa): la estructura del formulario es la misma para todas las empresas.

CREATE TABLE IF NOT EXISTS sri_form103_casilleros (
    id              SERIAL PRIMARY KEY,
    casillero_base  VARCHAR(6),
    casillero_valor VARCHAR(6),
    descripcion     TEXT NOT NULL,
    seccion         VARCHAR(20) NOT NULL,
    orden           INTEGER NOT NULL,
    indent          SMALLINT NOT NULL DEFAULT 0,
    bold            BOOLEAN NOT NULL DEFAULT false,
    tipo            VARCHAR(20) NOT NULL DEFAULT 'concepto', -- concepto | subtotal | total | informativo
    formula_base    VARCHAR(60),
    formula_valor   VARCHAR(60),
    eliminado       BOOLEAN NOT NULL DEFAULT false,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP,
    created_by      INTEGER,
    updated_by      INTEGER,
    deleted_by      INTEGER
);

TRUNCATE TABLE sri_form103_casilleros;

INSERT INTO sri_form103_casilleros
    (casillero_base, casillero_valor, descripcion, seccion, orden, indent, bold, tipo, formula_base, formula_valor)
VALUES
('302', '352', 'En relación de dependencia que supera o no la base desgravada', 'NACIONAL', 10, 0, false, 'concepto', NULL, NULL),
('303', '353', 'Servicios: Honorarios profesionales', 'NACIONAL', 20, 0, false, 'concepto', NULL, NULL),
('304', '354', 'Servicios: Predomina el intelecto', 'NACIONAL', 30, 0, false, 'concepto', NULL, NULL),
('307', '357', 'Servicios: Predomina mano de obra', 'NACIONAL', 40, 0, false, 'concepto', NULL, NULL),
('308', '358', 'Utilización o aprovechamiento de la imagen o renombre', 'NACIONAL', 50, 0, false, 'concepto', NULL, NULL),
('309', '359', 'Publicidad y comunicación', 'NACIONAL', 60, 0, false, 'concepto', NULL, NULL),
('310', '360', 'Transporte privado de pasajeros o servicio público o privado de carga', 'NACIONAL', 70, 0, false, 'concepto', NULL, NULL),
('311', '361', 'A través de liquidaciones de compra (nivel cultural o rusticidad)', 'NACIONAL', 80, 0, false, 'concepto', NULL, NULL),
('312', '362', 'Transferencia de bienes muebles de naturaleza corporal', 'NACIONAL', 90, 0, false, 'concepto', NULL, NULL),
('314', '364', 'Por regalías, derechos de autor, marcas, patentes y similares', 'NACIONAL', 100, 0, false, 'concepto', NULL, NULL),
('319', '369', 'Arrendamiento: Mercantil', 'NACIONAL', 110, 0, false, 'concepto', NULL, NULL),
('320', '370', 'Arrendamiento: Bienes inmuebles', 'NACIONAL', 120, 0, false, 'concepto', NULL, NULL),
('322', '372', 'Seguros y reaseguros (primas y cesiones)', 'NACIONAL', 130, 0, false, 'concepto', NULL, NULL),
('323', '373', 'Rendimientos financieros', 'NACIONAL', 140, 0, false, 'concepto', NULL, NULL),
('324', '374', 'Rendimientos financieros entre instituciones del sistema financiero y entidades economía popular y solidaria', 'NACIONAL', 150, 0, false, 'concepto', NULL, NULL),
('325', '375', 'Anticipo dividendos', 'NACIONAL', 160, 0, false, 'concepto', NULL, NULL),
('326', '376', 'Dividendos distribuidos que correspondan al Impto. a la Renta único establecido en el Art. 27 de la LRTI', 'NACIONAL', 170, 0, false, 'concepto', NULL, NULL),
('327', '377', 'Dividendos distribuidos a personas naturales residentes', 'NACIONAL', 180, 0, false, 'concepto', NULL, NULL),
('328', '378', 'Dividendos distribuidos a sociedades residentes', 'NACIONAL', 190, 0, false, 'concepto', NULL, NULL),
('329', '379', 'Dividendos distribuidos a fideicomisos residentes', 'NACIONAL', 200, 0, false, 'concepto', NULL, NULL),
('330', '380', 'Dividendos gravados distribuidos en acciones (reinversión de utilidades sin derecho a reducción tarifa IR)', 'NACIONAL', 210, 0, false, 'concepto', NULL, NULL),
('331', NULL, 'Dividendos exentos distribuidos en acciones (reinversión de utilidades con derecho a reducción tarifa IR)', 'NACIONAL', 220, 0, false, 'concepto', NULL, NULL),
('332', NULL, 'Pagos de bienes o servicios no sujetos a retención', 'NACIONAL', 230, 0, false, 'concepto', NULL, NULL),
('333', '383', 'Enajenación de derechos representativos de capital y otros derechos cotizados en bolsa ecuatoriana', 'NACIONAL', 240, 0, false, 'concepto', NULL, NULL),
('334', '384', 'Enajenación de derechos representativos de capital y otros derechos no cotizados en bolsa ecuatoriana', 'NACIONAL', 250, 0, false, 'concepto', NULL, NULL),
('335', '385', 'Loterías, rifas, apuestas y similares', 'NACIONAL', 260, 0, false, 'concepto', NULL, NULL),
('336', '386', 'Venta de combustibles: A comercializadoras', 'NACIONAL', 270, 0, false, 'concepto', NULL, NULL),
('337', '387', 'Venta de combustibles: A distribuidores', 'NACIONAL', 280, 0, false, 'concepto', NULL, NULL),
('338', '388', 'Compra local de banano a productor', 'NACIONAL', 290, 0, false, 'concepto', NULL, NULL),
('339', '389', 'Liquidación impuesto único a la venta local de banano de producción propia', 'NACIONAL', 300, 0, false, 'concepto', NULL, NULL),
('340', '390', 'Impuesto único a la exportación de banano de producción propia - Componente 1', 'NACIONAL', 310, 0, false, 'concepto', NULL, NULL),
('341', '391', 'Impuesto único a la exportación de banano de producción propia - Componente 2', 'NACIONAL', 320, 0, false, 'concepto', NULL, NULL),
('342', '392', 'Impuesto único a la exportación de banano producido por terceros', 'NACIONAL', 330, 0, false, 'concepto', NULL, NULL),
('343', '393', 'Otras retenciones: Aplicables el 1%', 'NACIONAL', 340, 0, false, 'concepto', NULL, NULL),
('344', '394', 'Otras retenciones: Aplicables el 2%', 'NACIONAL', 350, 0, false, 'concepto', NULL, NULL),
('345', '395', 'Otras retenciones: Aplicables el 8%', 'NACIONAL', 360, 0, false, 'concepto', NULL, NULL),
('346', '396', 'Otras retenciones: Aplicables a otros porcentajes', 'NACIONAL', 370, 0, false, 'concepto', NULL, NULL),
('349', '399', 'SUBTOTAL OPERACIONES EFECTUADAS EN EL PAIS', 'NACIONAL', 380, 0, true, 'subtotal', 'SUM_NACIONAL_BASE', 'SUM_NACIONAL_VALOR'),
('402', '452', 'Con convenio de doble tributación: Intereses por financiamiento de proveedores', 'EXT_CONVENIO', 390, 0, false, 'concepto', NULL, NULL),
('403', '453', 'Con convenio de doble tributación: Intereses de créditos', 'EXT_CONVENIO', 400, 0, false, 'concepto', NULL, NULL),
('404', '454', 'Con convenio de doble tributación: Anticipo de dividendos', 'EXT_CONVENIO', 410, 0, false, 'concepto', NULL, NULL),
('405', NULL, 'Con convenio de doble tributación: Dividendos distribuidos a personas naturales', 'EXT_CONVENIO', 420, 0, false, 'concepto', NULL, NULL),
('406', '456', 'Con convenio de doble tributación: Dividendos distribuidos a sociedades', 'EXT_CONVENIO', 430, 0, false, 'concepto', NULL, NULL),
('407', '457', 'Con convenio de doble tributación: Dividendos distribuidos a fideicomisos', 'EXT_CONVENIO', 440, 0, false, 'concepto', NULL, NULL),
('408', '458', 'Con convenio de doble tributación: Enajenación de derechos representativos de capital y otros derechos', 'EXT_CONVENIO', 450, 0, false, 'concepto', NULL, NULL),
('409', '459', 'Con convenio de doble tributación: Seguros y reaseguros (primas y cesiones)', 'EXT_CONVENIO', 460, 0, false, 'concepto', NULL, NULL),
('410', '460', 'Con convenio de doble tributación: Servicios técnicos, administrativos o de consultoría y regalías', 'EXT_CONVENIO', 470, 0, false, 'concepto', NULL, NULL),
('411', '461', 'Con convenio de doble tributación: Otros conceptos de ingresos gravados', 'EXT_CONVENIO', 480, 0, false, 'concepto', NULL, NULL),
('412', NULL, 'Con convenio de doble tributación: Otros pagos al exterior no sujetos a retención', 'EXT_CONVENIO', 490, 0, false, 'concepto', NULL, NULL),
('413', '463', 'Sin convenio de doble tributación: Intereses por financiamiento de proveedores', 'EXT_SINCONVENIO', 500, 0, false, 'concepto', NULL, NULL),
('414', '464', 'Sin convenio de doble tributación: Intereses de créditos', 'EXT_SINCONVENIO', 510, 0, false, 'concepto', NULL, NULL),
('415', '465', 'Sin convenio de doble tributación: Anticipo de dividendos', 'EXT_SINCONVENIO', 520, 0, false, 'concepto', NULL, NULL),
('416', NULL, 'Sin convenio de doble tributación: Dividendos distribuidos a personas naturales', 'EXT_SINCONVENIO', 530, 0, false, 'concepto', NULL, NULL),
('417', '467', 'Sin convenio de doble tributación: Dividendos distribuidos a sociedades', 'EXT_SINCONVENIO', 540, 0, false, 'concepto', NULL, NULL),
('418', '468', 'Sin convenio de doble tributación: Dividendos distribuidos a fideicomisos', 'EXT_SINCONVENIO', 550, 0, false, 'concepto', NULL, NULL),
('419', '469', 'Sin convenio de doble tributación: Enajenación de derechos representativos de capital y otros derechos', 'EXT_SINCONVENIO', 560, 0, false, 'concepto', NULL, NULL),
('420', '470', 'Sin convenio de doble tributación: Seguros y reaseguros (primas y cesiones)', 'EXT_SINCONVENIO', 570, 0, false, 'concepto', NULL, NULL),
('421', '471', 'Sin convenio de doble tributación: Servicios técnicos, administrativos o de consultoría y regalías', 'EXT_SINCONVENIO', 580, 0, false, 'concepto', NULL, NULL),
('422', '472', 'Sin convenio de doble tributación: Otros conceptos de ingresos gravados', 'EXT_SINCONVENIO', 590, 0, false, 'concepto', NULL, NULL),
('423', NULL, 'Sin convenio de doble tributación: Otros pagos al exterior no sujetos a retención', 'EXT_SINCONVENIO', 600, 0, false, 'concepto', NULL, NULL),
('424', '474', 'Paraísos fiscales o regímenes fiscales preferentes: Intereses', 'EXT_PARAISO', 610, 0, false, 'concepto', NULL, NULL),
('425', '475', 'Paraísos fiscales o regímenes fiscales preferentes: Anticipo de dividendos', 'EXT_PARAISO', 620, 0, false, 'concepto', NULL, NULL),
('426', '476', 'Paraísos fiscales o regímenes fiscales preferentes: Dividendos distribuidos a personas naturales', 'EXT_PARAISO', 630, 0, false, 'concepto', NULL, NULL),
('427', '477', 'Paraísos fiscales o regímenes fiscales preferentes: Dividendos distribuidos a sociedades', 'EXT_PARAISO', 640, 0, false, 'concepto', NULL, NULL),
('428', '478', 'Paraísos fiscales o regímenes fiscales preferentes: Dividendos distribuidos a fideicomisos', 'EXT_PARAISO', 650, 0, false, 'concepto', NULL, NULL),
('429', '479', 'Paraísos fiscales o regímenes fiscales preferentes: Enajenación de derechos representativos de capital y otros derechos', 'EXT_PARAISO', 660, 0, false, 'concepto', NULL, NULL),
('430', '480', 'Paraísos fiscales o regímenes fiscales preferentes: Seguros y reaseguros (primas y cesiones)', 'EXT_PARAISO', 670, 0, false, 'concepto', NULL, NULL),
('431', '481', 'Paraísos fiscales o regímenes fiscales preferentes: Servicios técnicos, administrativos o de consultoría y regalías', 'EXT_PARAISO', 680, 0, false, 'concepto', NULL, NULL),
('432', '482', 'Paraísos fiscales o regímenes fiscales preferentes: Otros conceptos de ingresos gravados', 'EXT_PARAISO', 690, 0, false, 'concepto', NULL, NULL),
('433', NULL, 'Paraísos fiscales o regímenes fiscales preferentes: Otros pagos al exterior no sujetos a retención', 'EXT_PARAISO', 700, 0, false, 'concepto', NULL, NULL),
('497', '498', 'SUBTOTAL OPERACIONES EFECTUADAS CON EL EXTERIOR', 'EXTERIOR', 710, 0, true, 'subtotal', 'SUM_EXTERIOR_BASE', 'SUM_EXTERIOR_VALOR'),
(NULL, '499', 'TOTAL DE RETENCIÓN DE IMPUESTO A LA RENTA (Campos 399+498)', 'TOTAL', 720, 0, true, 'total', NULL, '399+498'),
(NULL, '890', 'Pago previo (informativo, para declaraciones sustitutivas)', 'INFORMATIVO', 730, 0, false, 'informativo', NULL, NULL),
(NULL, '897', 'Interés (detalle de imputación al pago)', 'INFORMATIVO', 740, 0, false, 'informativo', NULL, NULL),
(NULL, '898', 'Impuesto (detalle de imputación al pago)', 'INFORMATIVO', 750, 0, false, 'informativo', NULL, NULL),
(NULL, '899', 'Multa (detalle de imputación al pago)', 'INFORMATIVO', 760, 0, false, 'informativo', NULL, NULL),
(NULL, '902', 'Total impuesto a pagar (499-898)', 'INFORMATIVO', 770, 0, false, 'informativo', NULL, NULL),
(NULL, '903', 'Interés por mora', 'INFORMATIVO', 780, 0, false, 'informativo', NULL, NULL),
(NULL, '904', 'Multa', 'INFORMATIVO', 790, 0, false, 'informativo', NULL, NULL),
(NULL, '999', 'Total pagado', 'INFORMATIVO', 800, 0, false, 'informativo', NULL, NULL);

-- Reutilizar la tabla genérica de movimientos de declaración (ya usada por
-- Declaración IVA / Form 104) para el Form 103, distinguiendo por 'formulario'.
ALTER TABLE casilleros_declaracion_sri ADD COLUMN IF NOT EXISTS formulario VARCHAR(3) NOT NULL DEFAULT '104';
COMMENT ON COLUMN casilleros_declaracion_sri.formulario IS '104 = Declaración IVA, 103 = Declaración Retenciones en la Fuente';
